import "antd/lib/input/style/css"
import "antd/lib/select/style/css"
import "antd/lib/time-picker/style/css"
import "antd/lib/date-picker/style/css"
import "antd/lib/form/style/css"
import "antd/lib/icon/style/css"
import "antd/lib/button/style/css"
import "antd/lib/cascader/style/css"
import "antd/lib/table/style/css"
import "antd/lib/modal/style/css"

import "../../lib/style/style.css"
